"""Test des 6 visionneuses dans les deux aperçus Fandom (Playwright, hors ligne).
Usage : python3 t_visionneuses.py  -> captures dans work/lightbox/test/cap/"""
import pathlib, sys
from playwright.sync_api import sync_playwright
R = pathlib.Path('/home/user/resultat/modele-wiki-fandom')
C = pathlib.Path(__file__).parent / 'cap'; C.mkdir(exist_ok=True)
ok = []; bad = []
def check(name, cond):
    (ok if cond else bad).append(name); print(('OK  ' if cond else 'ÉCHEC ') + name)

with sync_playwright() as p:
    b = p.chromium.launch()
    errs = []
    # ---------------- WEB ----------------
    ctx = b.new_context(viewport={'width': 1280, 'height': 800}); ctx.set_offline(True)
    pg = ctx.new_page(); pg.on('pageerror', lambda e: errs.append(str(e)))
    pg.goto((R / 'apercu-fandom-web.html').as_uri()); pg.wait_for_timeout(400)
    check('web: 11 images', pg.eval_on_selector_all('.mw-parser-output img', 'l=>l.length') == 11)
    check('web: sélecteur 3 options', pg.eval_on_selector_all('.demo select option', 'l=>l.length') == 3)
    check('web : « la mienne » par défaut', pg.eval_on_selector('.demo select', 'e=>e.value') == 'mine')
    pg.select_option('.demo select', 'f26'); pg.wait_for_timeout(50)
    # f26
    pg.click('.portable-infobox img'); pg.wait_for_timeout(300)
    check('f26 ouverte', pg.is_visible('.lbx-f26'))
    check('f26 titre', pg.inner_text('.lbx-f26 h1') == 'Example.jpg')
    check('f26 progression', 'de 11' in pg.inner_text('.lbx-f26 .f26-prog'))
    check('f26 ?file=', 'file=Example.jpg' in pg.url)
    check('f26 flèche précédente masquée au début', not pg.is_visible('.lbx-f26 .f26-arr.prev'))
    pg.screenshot(path=str(C / 'web_f26.jpg'), quality=80)
    pg.keyboard.press('ArrowRight'); pg.wait_for_timeout(100)
    check('f26 → image 2', pg.inner_text('.lbx-f26 h1') == 'Example1.png')
    pg.mouse.move(640, 400); pg.wait_for_timeout(1500)
    check('f26 barres masquées après 1,2 s', 'oh' in pg.get_attribute('.lbx-f26', 'class'))
    pg.mouse.move(700, 420); pg.wait_for_timeout(150)
    pg.click('.lbx-f26 .f26-share'); pg.wait_for_timeout(100)
    check('f26 panneau Partager', pg.is_visible('.lbx-f26 .shp'))
    pg.screenshot(path=str(C / 'web_f26_share.jpg'), quality=80)
    pg.keyboard.press('Escape'); pg.keyboard.press('Escape'); pg.wait_for_timeout(100)
    check('f26 fermée (Échap)', not pg.is_visible('.lbx-f26'))
    check('?file= retiré', 'file=' not in pg.url)
    # dark
    pg.click('#themeBtn'); pg.click('.lbx-gallery img >> nth=2'); pg.wait_for_timeout(300)
    pg.screenshot(path=str(C / 'web_f26_sombre.jpg'), quality=80); pg.keyboard.press('Escape'); pg.click('#themeBtn')
    # oasis
    pg.select_option('.demo select', 'oasis'); pg.wait_for_timeout(50)
    pg.click('.lbx-gallery img >> nth=0'); pg.wait_for_timeout(300)
    check('oasis ouverte', pg.is_visible('.lbx-oasis .oa-modal'))
    bb = pg.eval_on_selector('.lbx-oasis .oa-modal', 'e=>[e.offsetWidth,e.offsetHeight]')
    check('oasis 1010x628', bb == [1010, 628])
    pg.screenshot(path=str(C / 'web_oasis.jpg'), quality=80)
    pg.mouse.click(1100, 350); pg.wait_for_timeout(100)
    check('oasis clic moitié droite → suivante', pg.inner_text('.lbx-oasis h1') == 'Example2.png')
    pg.keyboard.press('Escape'); pg.wait_for_timeout(50)
    # mine
    pg.select_option('.demo select', 'mine')
    pg.click('.lbx-gallery img >> nth=1'); pg.wait_for_timeout(300)
    check('mienne ouverte', pg.is_visible('.flb'))
    pg.mouse.click(640, 400); pg.wait_for_timeout(450)
    check("mienne web : clic sur l'image ne ferme pas", pg.is_visible('.flb'))
    pg.click('.flb .flb-info-top'); pg.wait_for_timeout(100)
    check('mienne web : bouton infos en haut', pg.is_visible('.flb .flb-dlg'))
    pg.keyboard.press('Escape'); pg.wait_for_timeout(100)
    check('mienne web : Échap ferme d\'abord la fenêtre infos', pg.is_visible('.flb') and not pg.is_visible('.flb .flb-dlg'))
    pg.mouse.click(30, 200); pg.wait_for_timeout(200)
    check('mienne web : clic dans le vide ferme', not pg.is_visible('.flb'))
    pg.click('.lbx-gallery img >> nth=1'); pg.wait_for_timeout(300)
    pg.screenshot(path=str(C / 'web_mine.jpg'), quality=80); pg.keyboard.press('Escape')
    pg.select_option('.demo select', 'f26')
    ctx.close()
    # ---------------- WEB sur téléphone (tactile, comme sa capture) ----------------
    ctx = b.new_context(viewport={'width': 412, 'height': 915}, device_scale_factor=2.625, is_mobile=True, has_touch=True); ctx.set_offline(True)
    pg = ctx.new_page(); pg.on('pageerror', lambda e: errs.append(str(e)))
    pg.goto((R / 'apercu-fandom-web.html').as_uri()); pg.wait_for_timeout(400)
    pg.evaluate("localStorage.clear()"); pg.reload(); pg.wait_for_timeout(300)
    pg.select_option('.demo select', 'f26'); pg.wait_for_timeout(50)
    pg.click('#themeBtn'); pg.tap('.portable-infobox img'); pg.wait_for_timeout(3500)
    check('f26 tactile : barres épinglées', 'pinned' in pg.get_attribute('.lbx-f26', 'class') and 'oh' not in pg.get_attribute('.lbx-f26', 'class'))
    check('f26 tactile : cadenas caché', not pg.is_visible('.lbx-f26 .f26-pin'))
    pg.screenshot(path=str(C / 'web_f26_tactile.jpg'), quality=80)
    ctx.close()
    # ---------------- MOBILE ----------------
    dev = {k: v for k, v in p.devices['Pixel 7'].items() if k != 'default_browser_type'}
    ctx = b.new_context(**dev); ctx.set_offline(True)
    pg = ctx.new_page(); pg.on('pageerror', lambda e: errs.append(str(e)))
    pg.goto((R / 'apercu-fandom-mobile.html').as_uri()); pg.wait_for_timeout(400)
    check('mobile: sélecteurs', pg.eval_on_selector_all('select[data-lbx-select]', 'l=>l.length') == 2)
    check('mobile : « la mienne » par défaut', pg.eval_on_selector('select[data-lbx-select]', 'e=>e.value') == 'mine')
    pg.select_option('select[data-lbx-select] >> nth=0', 'fm25'); pg.wait_for_timeout(50)
    pg.tap('.portable-infobox img'); pg.wait_for_timeout(400)
    check('fm25 ouverte', pg.is_visible('.lbx-fm25'))
    check('fm25 infobox seule : pas de vignettes', not pg.is_visible('.lbx-fm25 .m-strip'))
    pg.screenshot(path=str(C / 'mob_fm25_infobox.jpg'), quality=80)
    pg.tap('.lbx-fm25 .m-x'); pg.wait_for_timeout(200)
    g = pg.locator('.lbx-gallery img').nth(0); g.scroll_into_view_if_needed(); g.tap(); pg.wait_for_timeout(400)
    check('fm25 galerie : 10 vignettes', pg.eval_on_selector_all('.lbx-fm25 .m-th', 'l=>l.length') == 10)
    check('fm25 compteur 1/10', pg.inner_text('.lbx-fm25 .m-cnt') == '1/10')
    pg.screenshot(path=str(C / 'mob_fm25_galerie.jpg'), quality=80)
    pg.keyboard.press('ArrowLeft'); pg.wait_for_timeout(50)
    check('fm25 pas de boucle', pg.inner_text('.lbx-fm25 .m-cnt') == '1/10')
    pg.tap('.lbx-fm25 .m-act.info'); pg.wait_for_timeout(100)
    check('fm25 fenêtre infos', pg.is_visible('.lbx-fm25 .m-dlg'))
    pg.screenshot(path=str(C / 'mob_fm25_infos.jpg'), quality=80)
    pg.tap('.lbx-fm25 .m-dlg .acts button'); pg.keyboard.press('Escape'); pg.wait_for_timeout(100)
    # flèches expérience
    pg.select_option('.lbx-demo select', 'fm25'); pg.check('.lbx-demo [data-lbx-arrows] input')
    g.tap(); pg.wait_for_timeout(300)
    check('fm25 flèches visibles (option)', pg.is_visible('.lbx-fm25 .m-arr.next'))
    pg.screenshot(path=str(C / 'mob_fm25_fleches.jpg'), quality=80); pg.keyboard.press('Escape')
    pg.uncheck('.lbx-demo [data-lbx-arrows] input')
    # mw
    pg.select_option('.lbx-demo select', 'mw'); g.tap(); pg.wait_for_timeout(400)
    check('mw ouverte', pg.is_visible('.lbx-mw'))
    pg.keyboard.press('ArrowLeft'); pg.wait_for_timeout(50)
    check('mw boucle 1→10', pg.inner_text('.lbx-mw .m-cnt') == '10/10')
    pg.screenshot(path=str(C / 'mob_mw.jpg'), quality=80)
    # swipe via CDP touch
    cdp = ctx.new_cdp_session(pg)
    def swipe(x0, x1, y=400):
        cdp.send('Input.dispatchTouchEvent', {'type': 'touchStart', 'touchPoints': [{'x': x0, 'y': y}]})
        for k in range(1, 6): cdp.send('Input.dispatchTouchEvent', {'type': 'touchMove', 'touchPoints': [{'x': x0 + (x1 - x0) * k / 5, 'y': y}]}); pg.wait_for_timeout(16)
        cdp.send('Input.dispatchTouchEvent', {'type': 'touchEnd', 'touchPoints': []})
    swipe(300, 80); pg.wait_for_timeout(150)
    check('mw glisser → 1/10', pg.inner_text('.lbx-mw .m-cnt') == '1/10')
    pg.keyboard.press('Escape'); pg.wait_for_timeout(100)
    check('mw fermée', not pg.is_visible('.lbx-mw'))
    # ----- la mienne (tour 78) -----
    pg.select_option('.lbx-demo select', 'mine')
    pg.locator('.portable-infobox img').scroll_into_view_if_needed(); pg.tap('.portable-infobox img'); pg.wait_for_timeout(400)
    check('mienne mobile : compteur « 1 / 11 » visible', pg.is_visible('.flb .flb-cnt-mob') and pg.inner_text('.flb .flb-cnt-mob') == '1 / 11')
    bx = pg.eval_on_selector('.flb .flb-cnt', 'e=>{const r=e.getBoundingClientRect();return [Math.round(r.left+r.width/2), Math.round(r.bottom)]}')
    check('mienne mobile : compteur en bas, centré', abs(bx[0] - 206) < 4 and bx[1] > 650)
    col = pg.eval_on_selector('.flb .flb-title', 'e=>getComputedStyle(e).color')
    check("mienne mobile : titre en blanc (tour 85)", col == 'rgb(255, 255, 255)' and pg.inner_text('.flb .flb-title') == 'Example.jpg')
    xr = pg.eval_on_selector('.flb .flb-x', 'e=>getComputedStyle(e).borderRadius')
    check('mienne mobile : ✕ rond', xr == '50%')
    pg.screenshot(path=str(C / 'mob_mine_seule.jpg'), quality=80)
    st = pg.eval_on_selector('.flb .flb-cnt', 'e=>[getComputedStyle(e).fontWeight,getComputedStyle(e).color]')
    check('mienne : chiffres gras #e6e6e6', st == ['700', 'rgb(230, 230, 230)'])
    bg = pg.eval_on_selector('.flb .flb-bot', 'e=>getComputedStyle(e).backgroundColor')
    check('mienne : bande transparente en bas', bg == 'rgba(0, 0, 0, 0.6)')
    th = pg.eval_on_selector('.flb .flb-th:not(.on)', 'e=>{const c=getComputedStyle(e),i=getComputedStyle(e.querySelector("img"));return [i.width,i.borderTopWidth,c.backgroundColor,Math.round(document.querySelector(".flb .flb-th").getBoundingClientRect().left)]}')
    check('mienne mobile : vignettes 44 px, encadré gris, à gauche (18 px)', th == ['44px', '2px', 'rgb(34, 34, 34)', 18])
    hb = pg.eval_on_selector('.flb .flb-bot', 'e=>Math.round(e.getBoundingClientRect().height)')
    check('mienne mobile : bande 95 px, sans ligne grise', hb == 95 and pg.eval_on_selector('.flb .flb-bot', 'e=>getComputedStyle(e).borderTopWidth') == '0px')
    check('mienne mobile : pas de flèches dans la bande', not pg.is_visible('.flb .flb-sr'))
    tt = pg.eval_on_selector('.flb .flb-title', 'e=>{const c=getComputedStyle(e),r=e.getBoundingClientRect();return [c.fontSize,c.lineHeight,Math.round(r.left),Math.round(r.top)]}')
    check('mienne mobile : titre 16/20 en haut à gauche (centré dans la barre)', tt[:3] == ['16px', '20px', 20] and tt[3] in (18, 19))
    fx = pg.evaluate('(()=>{const f=document.querySelector(".flb"),v=f.querySelector(".flb-view").getBoundingClientRect(),c=f.querySelector(".flb-capm");return [getComputedStyle(f).backgroundColor,getComputedStyle(f.querySelector(".flb-t1")).backgroundColor,Math.round(v.left),Math.round(v.top),Math.round(innerWidth-v.right),c.hidden,c.textContent]})()')
    check('mienne mobile : fond 95 % (Atelier), sans demi-barre, contour 15 px', fx[:5] == ['rgba(6, 6, 8, 0.95)', 'rgba(0, 0, 0, 0)', 15, 15, 15])
    pg.tap('.flb .flb-info-bot'); pg.wait_for_timeout(150)
    check('mienne : bouton infos ouvre la fenêtre', pg.is_visible('.flb .flb-dlg') and 'Jr Mime' in pg.inner_text('.flb .flb-dlg'))
    pg.screenshot(path=str(C / 'mob_mine_infos.jpg'), quality=80)
    pg.tap('.flb .flb-dlg-act button'); pg.wait_for_timeout(150)
    check('mienne : « Fermer » ferme la fenêtre, pas la visionneuse', not pg.is_visible('.flb .flb-dlg') and pg.is_visible('.flb'))
    pg.tap('.flb .flb-img'); pg.wait_for_timeout(450)
    check("mienne : toucher l'image masque l'interface (sans fermer)", pg.is_visible('.flb') and 'flb-ui-hidden' in pg.get_attribute('.flb', 'class'))
    pg.touchscreen.tap(206, 150); pg.wait_for_timeout(200)
    check('mienne : toucher le vide ferme', not pg.is_visible('.flb'))
    g.scroll_into_view_if_needed(); g.tap(); pg.wait_for_timeout(400)
    cdp.send('Input.dispatchTouchEvent', {'type': 'touchStart', 'touchPoints': [{'x': 300, 'y': 420}]})
    for k in range(1, 6): cdp.send('Input.dispatchTouchEvent', {'type': 'touchMove', 'touchPoints': [{'x': 300 - 44 * k, 'y': 420}]}); pg.wait_for_timeout(16)
    tf = pg.eval_on_selector('.flb .flb-img', 'e=>e.style.transform')
    check("mienne : l'image ne suit plus le doigt", tf in ('', 'none'))
    cdp.send('Input.dispatchTouchEvent', {'type': 'touchEnd', 'touchPoints': []}); pg.wait_for_timeout(200)
    check('mienne : geste rapide → image suivante', pg.inner_text('.flb .flb-cnt-mob') == '3 / 11')
    cp = pg.eval_on_selector('.flb .flb-capm', 'e=>{const c=getComputedStyle(e),r=e.getBoundingClientRect(),b=document.querySelector(".flb .flb-bot").getBoundingClientRect();return [e.textContent,c.fontSize,c.fontWeight,c.textAlign,c.backgroundColor,r.top>b.top&&r.bottom<b.bottom]}')
    check('mienne mobile : légende style Fandom 2025 (14 px, 300, à gauche, sans cadre, dans la bande)', cp == ['Légende 2', '14px', '300', 'left', 'rgba(0, 0, 0, 0)', True])
    st2 = pg.evaluate('(()=>{const f=document.querySelector(".flb"),a=f.querySelector(".flb-next"),x=f.querySelector(".flb-x"),c=getComputedStyle(a),cx=getComputedStyle(x);return [getComputedStyle(f).backdropFilter,Math.round(a.getBoundingClientRect().width),c.backgroundColor,c.borderRadius,cx.backgroundColor,getComputedStyle(a.querySelector(".flb-ic-m")).display,getComputedStyle(a.querySelector(".flb-ic-d")).display]})()')
    check('mienne mobile : page floutée 4 px, flèches 46 px et ✕ façon Atelier', st2 == ['blur(4px)', 46, 'rgba(12, 13, 16, 0.62)', '50%', 'rgba(255, 255, 255, 0.08)', 'block', 'none'])
    xb = pg.evaluate('(()=>{const x=document.querySelector(".flb .flb-x").getBoundingClientRect(),i=document.querySelector(".flb .flb-info-bot").getBoundingClientRect();return [Math.round(x.width),Math.round(innerWidth-x.right),Math.round(innerWidth-i.right)]})()')
    check('mienne mobile : ✕ 40 px à 16 px du bord, ⓘ à 18 px du bord', xb == [40, 16, 18])
    od = pg.evaluate('(()=>{const q=s=>document.querySelector(".flb "+s).getBoundingClientRect();return [q(".flb-row").bottom<=q(".flb-capm").top, q(".flb-capm").bottom<=q(".flb-strip").top]})()')
    check('mienne mobile : chiffres + ⓘ au-dessus de la légende, vignettes en dessous', od == [True, True])
    tb = pg.eval_on_selector('.flb .flb-top', 'e=>{const r=e.getBoundingClientRect(),v=document.querySelector(".flb .flb-view").getBoundingClientRect();return [getComputedStyle(e).backgroundColor,Math.round(r.top),Math.round(r.height),Math.round(v.top)]}')
    check("mienne mobile : barre noire 57 px sous le nom et le ✕, transparente comme la bande du bas (tour 94), l'image garde sa taille", tb == ['rgba(0, 0, 0, 0.6)', 0, 57, 15])
    pg.screenshot(path=str(C / 'mob_mine_galerie.jpg'), quality=80)
    pg.keyboard.press('Escape'); pg.wait_for_timeout(100)
    pg.select_option('.lbx-demo select', 'mw')
    # persistance
    pg.reload(); pg.wait_for_timeout(300)
    check('choix mémorisé', pg.eval_on_selector('.demo select', 's=>s.value') == 'mw')
    ctx.close(); b.close()
    check('aucune erreur JS', not errs)
    if errs: print(errs)
print(f'\n{len(ok)} OK / {len(bad)} échec(s)')
sys.exit(1 if bad else 0)
